CREATE TABLE user(
	nome VARCHAR(20) NOT NULL,
	senha VARCHAR(20) NOT NULL,
	email VARCHAR(20) NOT NULL,
	imageURL VARCHAR(60),
	id INT AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE album(
	id INT PRIMARY KEY IDENTITY(1,1),
	userId INT FOREIGN KEY REFERENCES user(id) NOT NULL
)

CREATE TABLE image(
	imageURL VARCHAR(60) NOT NULL,
	id INT PRIMARY KEY IDENTITY(1,1),
	userId INT FOREIGN KEY REFERENCES user(id) NOT NULL,
	albumId INT FOREIGN KEY REFERENCES user(id) NOT NULL
)
